const standardTextFields = [
  {
    boolean: patientRegister?.isNameInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'patient-register-name_input',
    labelClassName: 'text-sm',
    labelName: 'Nom',
    inputName: 'name',
    inputPlaceholder: 'Entrez votre nom',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: patientRegister?.isSurnameInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'patient-register-surname_input',
    labelClassName: 'text-sm',
    labelName: 'Prénom',
    inputName: 'surname',
    inputPlaceholder: 'Entrez votre prénom',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: patientRegister?.isBirthNameInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'patient-register-birthname_input',
    labelClassName: 'text-sm',
    labelName: 'Nom de naissance',
    inputName: 'birth_name',
    inputPlaceholder: 'Entrez votre nom de naissance',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: patientRegister?.isStreetNumberInput,
    divClassName: 'w-4/12 flex flex-col mb-4',
    inputId: 'patient-register-street_number_input',
    labelClassName: 'text-xs',
    labelName: 'N° de rue',
    inputName: 'street_number',
    inputPlaceholder: 'N° de rue',
    required: false,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: patientRegister?.isStreetNameInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'patient-register-street_name_input',
    labelClassName: 'text-xs',
    labelName: 'Nom de rue',
    inputName: 'street_name',
    inputPlaceholder: 'Nom de rue',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: patientRegister?.isPostalCodeInput,
    divClassName: 'w-1/2 flex flex-col mb-4',
    inputId: 'patient-register-postal_code_input',
    labelClassName: 'text-xs',
    labelName: 'Code postal',
    inputName: 'postal_code',
    inputPlaceholder: 'Code postal',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: patientRegister?.isCityInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'patient-register-city_input',
    labelClassName: 'text-xs',
    labelName: 'Ville',
    inputName: 'city',
    inputPlaceholder: 'Ville',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: patientRegister?.isAppointmentNumberInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'appointment-number_input',
    labelClassName: 'text-sm',
    labelName: 'Quantité séances prescrites',
    inputName: 'appointment_quantity',
    inputPlaceholder: 'Séances prescrites',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: generalInput?.isPatientMessageInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'patient-message-input',
    labelClassName: 'text-sm',
    labelName: 'Message',
    inputName: 'content',
    inputPlaceholder: 'Tapez votre message...',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: true,
    generalDivClassName: false,
    generalLabelClassName: true,
  },
  {
    boolean: adminTherapist?.isAdminTherapistAddNameInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'therapist-name_input',
    labelClassName: 'text-sm',
    labelName: 'Nom',
    inputName: 'name',
    inputPlaceholder: 'Entrez le nom du kiné',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminTherapist?.isAdminTherapistAddSurnameInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'therapist-surname_input',
    labelClassName: 'text-sm',
    labelName: 'Prénom',
    inputName: 'surname',
    inputPlaceholder: 'Entrez le prénom du kiné',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminTherapist?.isAdminTherapistAddLicenceCodeInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'therapist-licence-code_input',
    labelClassName: 'text-sm',
    labelName: 'Code ADELI',
    inputName: 'licence_code',
    inputPlaceholder: 'Entrez le code ADELI du kiné',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminTherapist?.isAdminTherapistAddDiplomaInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'therapist-diploma_input',
    labelClassName: 'text-sm',
    labelName: 'Diplôme',
    inputName: 'diploma',
    inputPlaceholder: 'Entrez le diplôme du kiné',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminTherapist?.isAdminTherapistAddExperienceInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'therapist-experience_input',
    labelClassName: 'text-sm',
    labelName: 'Expérience',
    inputName: 'experience',
    inputPlaceholder: "Entrez l'expérience du kiné",
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminTherapist?.isAdminTherapistAddSpecialtyInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'therapist-specialty_input',
    labelClassName: 'text-sm',
    labelName: 'Spécialité',
    inputName: 'specialty',
    inputPlaceholder: 'Entrez la spécialité du kiné',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminTherapist?.isAdminTherapistAddDescriptionInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'therapist-description_input',
    labelClassName: 'text-sm',
    labelName: 'Description du kiné',
    inputName: 'description',
    inputPlaceholder: 'Description du kinésithérapeute',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: true,
    generalDivClassName: false,
    generalLabelClassName: true,
  },
  {
    boolean: adminTherapist?.isAdminTherapistEditSurnameInput,
    divClassName: 'flex flex-row items-center gap-2 mb-2 w-full',
    inputId: 'therapist-surname_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6',
    labelName: 'Prénom',
    inputName: 'surname',
    inputPLaceholder: '',
    required: true,
    inputValue: therapistState.therapistSurname,
    inputOnChange: (e) => handleTherapistChange('surname', e.target.value),
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminTherapist?.isAdminTherapistEditNameInput,
    divClassName: 'flex flex-row items-center gap-2 mb-2 w-full',
    inputId: 'therapist-name_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6',
    labelName: 'Nom',
    inputName: 'name',
    inputPLaceholder: '',
    required: true,
    inputValue: therapistState.therapistName,
    inputOnChange: (e) => handleTherapistChange('name', e.target.value),
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminTherapist?.isAdminTherapistEditLicenceCodeInput,
    divClassName: 'flex flex-row items-center gap-2 mb-2 w-full',
    inputId: 'therapist-licence_code_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6',
    labelName: 'Code ADELI',
    inputName: 'licence_code',
    inputPLaceholder: '',
    required: true,
    inputValue: therapistState.therapistLicenceCode,
    inputOnChange: (e) => handleTherapistChange('licence_code', e.target.value),
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminTherapist?.isAdminTherapistEditDiplomaInput,
    divClassName: 'flex flex-row items-center gap-2 mb-2 w-full',
    inputId: 'therapist-diploma_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6',
    labelName: 'Diplôme',
    inputName: 'diploma',
    inputPLaceholder: '',
    required: true,
    inputValue: therapistState.therapistDiploma,
    inputOnChange: (e) => handleTherapistChange('diploma', e.target.value),
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminTherapist?.isAdminTherapistEditExperienceInput,
    divClassName: 'flex flex-row items-center gap-2 mb-2 w-full',
    inputId: 'therapist-experience_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6',
    labelName: 'Expérience',
    inputName: 'experience',
    inputPLaceholder: '',
    required: true,
    inputValue: therapistState.therapistExperience,
    inputOnChange: (e) => handleTherapistChange('experience', e.target.value),
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminTherapist?.isAdminTherapistSpecialtyInput,
    divClassName: 'flex flex-row items-center gap-2 mb-2 w-full',
    inputId: 'therapist-specialty_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6',
    labelName: 'Spécialité',
    inputName: 'specialty',
    inputPLaceholder: '',
    required: true,
    inputValue: therapistState.therapistSpecialty,
    inputOnChange: (e) => handleTherapistChange('specialty', e.target.value),
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminTherapist?.isAdminTherapistEditDescriptionInput,
    divClassName: 'flex flex-row items-center gap-2 mb-2 w-full',
    inputId: 'therapist-description_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6',
    labelName: 'Description',
    inputName: 'description',
    inputPLaceholder: '',
    required: true,
    inputValue: therapistState.therapistDescription,
    inputOnChange: (e) => handleTherapistChange('description', e.target.value),
    textArea: true,
    generalDivClassName: false,
    generalLabelClassName: true,
  },
  {
    boolean: adminAffliction?.isAdminAfflictionAddNameInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'affliction-name_input',
    labelClassName: 'text-sm',
    labelName: "Nom de l'affliction",
    inputName: 'name',
    inputPlaceholder: "Entrez le nom de l'affliction",
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminAffliction?.isAdminAfflictionAddLicenceCodeInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'affliction-insurance-code_input',
    labelClassName: 'text-sm',
    labelName: 'Cotation',
    inputName: 'insurance_code',
    inputPlaceholder: "Entrez la cotation de l'affliction",
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminAffliction?.isAdminAfflictionAddDescriptionInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'affliction-description_input',
    labelClassName: 'text-sm',
    labelName: 'Description',
    inputName: 'description',
    inputPlaceholder: "Description de l'affliction",
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: true,
    generalDivClassName: false,
    generalLabelClassName: true,
  },
  {
    boolean: adminAffliction?.isAdminAfflictionEditNameInput,
    divClassName: 'flex flex-row items-center gap-2 mb-2 w-full',
    inputId: 'affliction-name_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6',
    labelName: 'Nom',
    inputName: 'name',
    inputPLaceholder: '',
    required: true,
    inputValue: afflictionState.afflictionName,
    inputOnChange: (e) => handleAfflictionChange('name', e.target.value),
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminAffliction?.isAdminAfflictionEditLicenceCodeInput,
    divClassName: 'flex flex-row items-center gap-2 mb-2 w-full',
    inputId: 'affliction-insurance-code_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6',
    labelName: 'Cotation',
    inputName: 'insurance_code',
    inputPLaceholder: '',
    required: true,
    inputValue: afflictionState.afflictionInsuranceCode,
    inputOnChange: (e) =>
      handleAfflictionChange('insurance_code', e.target.value),
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminAffliction?.isAdminAfflictionEditDescriptionInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'affliction-description_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6 ',
    labelName: 'Description',
    inputName: 'description',
    inputPLaceholder: '',
    required: true,
    inputValue: afflictionState.afflictionDescription,
    inputOnChange: (e) => handleAfflictionChange('description', e.target.value),
    textArea: true,
    generalDivClassName: false,
    generalLabelClassName: true,
  },
  {
    boolean: adminMedic?.isAdminMedicAddNameInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'medic-name_input',
    labelClassName: 'text-sm',
    labelName: 'Nom',
    inputName: 'name',
    inputPlaceholder: 'Entrez le nom du médecin',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminMedic?.isAdminMedicAddSurnameInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'medic-surname_input',
    labelClassName: 'text-sm',
    labelName: 'Prénom',
    inputName: 'surname',
    inputPlaceholder: 'Entrez le prénom du médecin',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminMedic?.isAdminMedicAddLicenceCodeInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'medic-licence-code_input',
    labelClassName: 'text-sm',
    labelName: 'Code ADELI',
    inputName: 'licence_code',
    inputPlaceholder: 'Entrez le code ADELI du médecin',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminMedic?.isAdminMedicAddStreetNumberInput,
    divClassName: 'w-4/12 flex flex-col mb-4',
    inputId: 'medic-street_number_input',
    labelClassName: 'text-xs',
    labelName: 'N° de rue',
    inputName: 'street_number',
    inputPlaceholder: 'N° de rue',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminMedic?.isAdminMedicAddStreetNameInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'medic-street_name_input',
    labelClassName: 'text-xs',
    labelName: 'Nom de rue',
    inputName: 'street_name',
    inputPlaceholder: 'Entrez le nom de rue du médecin',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminMedic?.isAdminMedicAddPostalCodeInput,
    divClassName: 'w-1/3 flex flex-col mb-4',
    inputId: 'medic-postal_code_input',
    labelClassName: 'text-xs',
    labelName: 'Code postal',
    inputName: 'postal_code',
    inputPlaceholder: 'Code postal',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminMedic?.isAdminMedicAddCityInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'medic-city_input',
    labelClassName: 'text-xs',
    labelName: 'Ville',
    inputName: 'city',
    inputPlaceholder: 'Entrez la ville du médecin',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminMedic?.isAdminMedicEditNameInput,
    divClassName: 'flex flex-row items-center gap-2 mb-2 w-full',
    inputId: 'medic-name_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6',
    labelName: 'Nom',
    inputName: 'name',
    inputPLaceholder: '',
    required: true,
    inputValue: medicState.medicName,
    inputOnChange: (e) => handleMedicChange('name', e.target.value),
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminMedic?.isAdminMedicEditSurnameInput,
    divClassName: 'flex flex-row items-center gap-2 mb-2 w-full',
    inputId: 'medic-surname_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6',
    labelName: 'Prénom',
    inputName: 'surname',
    inputPLaceholder: '',
    required: true,
    inputValue: medicState.medicSurname,
    inputOnChange: (e) => handleMedicChange('surname', e.target.value),
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminMedic?.isAdminMedicEditLicenceCodeInput,
    divClassName: 'flex flex-row items-center gap-2 mb-2 w-full',
    inputId: 'medic-licence_code_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6',
    labelName: 'Code ADELI',
    inputName: 'licence_code',
    inputPLaceholder: '',
    required: true,
    inputValue: medicState.medicLicenceCode,
    inputOnChange: (e) => handleMedicChange('licence_code', e.target.value),
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminMedic?.isAdminMedicEditStreetNumberInput,
    divClassName: 'flex flex-row items-center gap-2 mb-2 w-full',
    inputId: 'medic-street_number_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6',
    labelName: 'N° de rue',
    inputName: 'street_number',
    inputPLaceholder: '',
    required: true,
    inputValue: medicState.medicStreetNumber,
    inputOnChange: (e) => handleMedicChange('street_number', e.target.value),
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminMedic?.isAdminMedicEditStreetNameInput,
    divClassName: 'flex flex-row items-center gap-2 mb-2 w-full',
    inputId: 'medic-street_name_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6',
    labelName: 'Nom de rue',
    inputName: 'street_name',
    inputPLaceholder: '',
    required: true,
    inputValue: medicState.medicStreetName,
    inputOnChange: (e) => handleMedicChange('street_name', e.target.value),
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminMedic?.isAdminMedicEditPostalCodeInput,
    divClassName: 'flex flex-row items-center gap-2 mb-2 w-full',
    inputId: 'medic-postal_code_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6',
    labelName: 'Code postal',
    inputName: 'postal_code',
    inputPLaceholder: '',
    required: true,
    inputValue: medicState.medicPostalCode,
    inputOnChange: (e) => handleMedicChange('postal_code', e.target.value),
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminMedic?.isAdminMedicEditCityInput,
    divClassName: 'flex flex-row items-center gap-2 mb-2 w-full',
    inputId: 'medic-city_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6',
    labelName: 'Ville',
    inputName: 'city',
    inputPLaceholder: '',
    required: true,
    inputValue: medicState.medicCity,
    inputOnChange: (e) => handleMedicChange('city', e.target.value),
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminInsurance?.isAdminInsuranceAddNameInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'insurance-name_input',
    labelClassName: 'text-sm',
    labelName: 'Nom',
    inputName: 'name',
    inputPlaceholder: "Entrez le nom de l'assurance",
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminInsurance?.isAdminInsuranceAddLicenceCodeInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'insurance-licence-code_input',
    labelClassName: 'text-sm',
    labelName: 'Code AMC',
    inputName: 'amc_code',
    inputPlaceholder: "Entrez le code AMC de l'assurance",
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminInsurance?.isAdminInsuranceAddStreetNumberInput,
    divClassName: 'w-1/3 flex flex-col mb-4',
    inputId: 'insurance-street_number_input',
    labelClassName: 'text-xs',
    labelName: 'N° de rue',
    inputName: 'street_number',
    inputPlaceholder: 'N° de rue',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminInsurance?.isAdminInsuranceAddStreetNameInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'insurance-street_name_input',
    labelClassName: 'text-xs',
    labelName: 'Nom de rue',
    inputName: 'street_name',
    inputPlaceholder: "Entrez le nom de rue de l'assurance",
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminInsurance?.isAdminInsuranceAddPostalCodeInput,
    divClassName: 'w-1/3 flex flex-col mb-4',
    inputId: 'insurance-postal_code_input',
    labelClassName: 'text-xs',
    labelName: 'Code postal',
    inputName: 'postal_code',
    inputPlaceholder: 'Code postal',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminInsurance?.isAdminInsuranceAddCityInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'insurance-city_input',
    labelClassName: 'text-xs',
    labelName: 'Ville',
    inputName: 'city',
    inputPlaceholder: "Entrez la ville de l'assurance",
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminInsurance?.isAdminInsuranceEditNameInput,
    divClassName: 'flex flex-row items-center gap-2 mb-2 w-full',
    inputId: 'insurance-name_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6',
    labelName: 'Nom',
    inputName: 'name',
    inputPLaceholder: '',
    required: true,
    inputValue: insuranceState.insuranceName,
    inputOnChange: (e) => handleInsuranceChange('name', e.target.value),
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminInsurance?.isAdminInsuranceEditAMCCodeInput,
    divClassName: 'flex flex-row items-center gap-2 mb-2 w-full',
    inputId: 'insurance-licence-code_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6',
    labelName: 'Code AMC',
    inputName: 'amc_code',
    inputPLaceholder: '',
    required: true,
    inputValue: insuranceState.insuranceAmcCode,
    inputOnChange: (e) => handleInsuranceChange('amc_code', e.target.value),
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminInsurance?.isAdminInsuranceEditStreetNumberInput,
    divClassName: 'flex flex-row items-center gap-2 mb-2 w-full',
    inputId: 'insurance-street_number_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6',
    labelName: 'N° de rue',
    inputName: 'street_number',
    inputPLaceholder: '',
    required: true,
    inputValue: insuranceState.insuranceStreetNumber,
    inputOnChange: (e) =>
      handleInsuranceChange('street_number', e.target.value),
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminInsurance?.isAdminInsuranceEditStreetNameInput,
    divClassName: 'flex flex-row items-center gap-2 mb-2 w-full',
    inputId: 'insurance-street_name_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6',
    labelName: 'Nom de rue',
    inputName: 'street_name',
    inputPLaceholder: '',
    required: true,
    inputValue: insuranceState.insuranceStreetName,
    inputOnChange: (e) => handleInsuranceChange('street_name', e.target.value),
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminInsurance?.isAdminInsuranceEditPostalCodeInput,
    divClassName: 'flex flex-row items-center gap-2 mb-2 w-full',
    inputId: 'insurance-postal_code_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6',
    labelName: 'Code postal',
    inputName: 'postal_code',
    inputPLaceholder: '',
    required: true,
    inputValue: insuranceState.insurancePostalCode,
    inputOnChange: (e) => handleInsuranceChange('postal_code', e.target.value),
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminInsurance?.isAdminInsuranceEditCityInput,
    divClassName: 'flex flex-row items-center gap-2 mb-2 w-full',
    inputId: 'insurance-city_input',
    labelClassName: 'text-base md:text-lg xl:text-xl 2xl:text-2xl w-1/6',
    labelName: 'Ville',
    inputName: 'city',
    inputPLaceholder: '',
    required: true,
    inputValue: insuranceState.insuranceCity,
    inputOnChange: (e) => handleInsuranceChange('city', e.target.value),
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
  {
    boolean: adminRegion?.isAdminRegionAddNameInput,
    divClassName: 'w-full flex flex-col mb-4',
    inputId: 'region-name_input',
    labelClassName: 'text-sm',
    labelName: 'Nom',
    inputName: 'name',
    inputPlaceholder: 'Entrez le nom de la région',
    required: true,
    inputValue: undefined,
    inputOnChange: undefined,
    textArea: false,
    generalDivClassName: true,
    generalLabelClassName: true,
  },
];
