import { IEntityStates } from '../../../../../@types/customInterfaces';

// Mapping object to dynamically group state based on boolean flag
export const adminPageEntityStates = ({
  isAdminTherapistsMain,
  isAdminTherapistMain,
  isAdminPatientsMain,
  isAdminPatientMain,
  isAdminAfflictionsMain,
  isAdminAfflictionMain,
  isAdminMedicsMain,
  isAdminMedicMain,
  isAdminInsurancesMain,
  isAdminInsuranceMain,
  allTherapists,
  setAllTherapists,
  therapist,
  setTherapist,
  therapistId,
  setTherapistId,
  allPatients,
  setAllPatients,
  patient,
  setPatient,
  patientId,
  setPatientId,
  allAfflictions,
  setAllAfflictions,
  affliction,
  setAffliction,
  afflictionId,
  setAfflictionId,
  allMedics,
  setAllMedics,
  medic,
  setMedic,
  medicId,
  setMedicId,
  allInsurances,
  setAllInsurances,
  insurance,
  setInsurance,
  insuranceId,
  setInsuranceId,
}: IEntityStates) => ({
  therapists: {
    entityType: 'therapist',
    isActive: isAdminTherapistsMain || isAdminTherapistMain,
    entities: allTherapists,
    setEntities: setAllTherapists,
    entity: therapist,
    setEntity: setTherapist,
    entityId: therapistId,
    setEntityId: setTherapistId,
  },
  patients: {
    entityType: 'patient',
    isActive: isAdminPatientsMain || isAdminPatientMain,
    entities: allPatients,
    setEntities: setAllPatients,
    entity: patient,
    setEntity: setPatient,
    entityId: patientId,
    setEntityId: setPatientId,
  },
  afflictions: {
    entityType: 'affliction',
    isActive: isAdminAfflictionsMain || isAdminAfflictionMain,
    entities: allAfflictions,
    setEntities: setAllAfflictions,
    entity: affliction,
    setEntity: setAffliction,
    entityId: afflictionId,
    setEntityId: setAfflictionId,
  },
  medics: {
    entityType: 'medic',
    isActive: isAdminMedicsMain || isAdminMedicMain,
    entities: allMedics,
    setEntities: setAllMedics,
    entity: medic,
    setEntity: setMedic,
    entityId: medicId,
    setEntityId: setMedicId,
  },
  insurances: {
    entityType: 'insurance',
    isActive: isAdminInsurancesMain || isAdminInsuranceMain,
    entities: allInsurances,
    setEntities: setAllInsurances,
    entity: insurance,
    setEntity: setInsurance,
    entityId: insuranceId,
    setEntityId: setInsuranceId,
  },
});
