/**
 * TableTitleRefactor Component
 *
 * This component renders the title of a table in the admin section, dynamically updating the content based on the
 * provided `tableTitle` and `entityStatus` props.
 * It uses the `getAdminTableTitleContent` function to generate the appropriate title based on the entity's current status.
 *
 * **Main Features:**
 * - Displays the title of the table, which can vary based on the status of the entity being displayed (e.g., "All therapists", "Active patients").
 * - Uses the `getAdminTableTitleContent` function to determine the final title based on the `tableTitle` and `entityStatus` values.
 * - The title is rendered with responsive styling that adjusts for different screen sizes.
 *
 * **Parameters:**
 * - `tableTitle` (`string`): The base title for the table (e.g., "All therapists", "All patients").
 * - `entityStatus` (`string`): The current status of the entity (e.g., 'all', 'active', 'inactive'). This is used to modify the title dynamically.
 *
 * **Usage Example:**
 * ```tsx
 * <TableTitleRefactor tableTitle="All therapists" entityStatus="active" />
 * ```
 * This will render the title based on the logic in `getAdminTableTitleContent` and the passed values of `tableTitle` and `entityStatus`.
 *
 * **Returns:**
 * - This component returns an `h2` element that contains the dynamic table title generated by `getAdminTableTitleContent`.
 *
 * **Styling:**
 * - The title is styled with `text-center` and other Tailwind CSS classes, adjusting for different screen sizes (e.g., `md:text-2xl` for larger screens).
 *
 * **Important Notes:**
 * - The `getAdminTableTitleContent` function is crucial in modifying the title based on the entity's status. It provides dynamic behavior to the title rendering.
 * - The title layout is responsive and changes according to the screen size, with a larger font size for medium and larger screens.
 */

import { getAdminTableTitleContent } from '../../../../../../../utils/componentUtils/pageComponents/functions/adminSection/AdminTable/getAdminTableTitleContent';

interface TableTitleRefactorProps {
  tableTitle: string;
  entityStatus: string;
}

export default function TableTitleRefactor({
  tableTitle,
  entityStatus,
}: TableTitleRefactorProps) {
  return (
    <h2 className="text-center md:text-2xl font-semibold mb-4 md:text-left ml-10">
      {getAdminTableTitleContent({ tableTitle, entityStatus })}
    </h2>
  );
}
